#ifndef WORKLOAD_H
#define WORKLOAD_H

#include <string>
#include <vector>
#include <fstream>

/**
 * Workload Parser for FreshDiskANN
 *
 * Parses JSONL workload files generated by WORKLOAD_GENERATOR
 * Supports three event types: INSERT, DELETE, QUERY
 */

enum EventType {
    EVENT_INSERT,
    EVENT_DELETE,
    EVENT_QUERY
};

struct WorkloadEvent {
    EventType type;
    unsigned timestamp;      // Milliseconds since start
    unsigned pointId;        // For INSERT/DELETE
    unsigned queryId;        // For QUERY
    std::vector<float> vector;  // For INSERT (D dimensions)

    WorkloadEvent() : type(EVENT_QUERY), timestamp(0), pointId(0), queryId(0) {}
};

/**
 * Workload class - parses and provides access to JSONL workload
 */
class Workload {
private:
    std::vector<WorkloadEvent> events;
    std::string scenario;
    unsigned totalInserts;
    unsigned totalDeletes;
    unsigned totalQueries;

public:
    /**
     * Constructor: Parse workload from JSONL file
     *
     * Expected JSON format per line:
     * {"type": "insert", "timestamp": 0, "point_id": 10000, "vector": [...]}
     * {"type": "delete", "timestamp": 100, "point_id": 42}
     * {"type": "query", "timestamp": 200, "query_id": 0}
     *
     * @param filename Path to JSONL workload file
     */
    Workload(const std::string& filename);

    /**
     * Get total number of events
     */
    size_t size() const { return events.size(); }

    /**
     * Get event at index
     */
    const WorkloadEvent& operator[](size_t idx) const { return events[idx]; }

    /**
     * Get statistics
     */
    unsigned getInsertCount() const { return totalInserts; }
    unsigned getDeleteCount() const { return totalDeletes; }
    unsigned getQueryCount() const { return totalQueries; }
    std::string getScenario() const { return scenario; }

    /**
     * Print workload summary
     */
    void printSummary() const;
};

/**
 * Simple JSON parser for workload events
 * (Minimal implementation - just what we need for JSONL parsing)
 */
class SimpleJSONParser {
public:
    /**
     * Parse a single JSONL line into a WorkloadEvent
     */
    static WorkloadEvent parseEvent(const std::string& jsonLine);

    static std::string extractString(const std::string& json, const std::string& key);
    static unsigned extractUnsigned(const std::string& json, const std::string& key);
    static std::vector<float> extractFloatArray(const std::string& json, const std::string& key);
};

#endif // WORKLOAD_H
